language: node_js
node_js:
  - "6"
after_success: deploy.sh
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
    node: 6
sudo: false
cahce:
  directories:
  - node_modules
